added JavaScript folder
kyle-kauzlarich/HacktoberAlgs pull request #2
Opened 2020-10-08 23:06 UTC by Stryyder

Still getting a feel for pull requests. Also, I'm curious what type of algorithms you're looking for. Any/All?

2020-10-08 23:13 UTC, kyle-kauzlarich commented
The folder is going to need a file inside of it before it shows up.
perhaps string reversal or your favorite algorithm?

2020-10-08 23:16 UTC, kyle-kauzlarich requested changes

2020-10-08 23:16 UTC, kyle-kauzlarich commented on Contributors.md
> +**Toby Glaze ** https://github.com/Stryyder
The bolded font will work once you remove the space between your last name and the trailing **

2020-10-09 04:13 UTC, Stryyder commented
I see that my changes have automatically showed up here - that was a little unexpected because I had only committed to my own fork (or so I thought). Forgive my ignorance on this workflow. This is all new to me.

2020-10-09 06:11 UTC, kyle-kauzlarich approved these changes

2020-10-09 06:11 UTC, merged